{% set name = "omnicloudmask" %}
{% set version = "1.7.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/omnicloudmask-{{ version }}.tar.gz
  sha256: 5583b9bb1e46469835bb61074c47a6037639e11323c9568bd87f059db4a7c1e9

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools
  run:
    - python >={{ python_min }}
    - gdown >=5.1.0
    - huggingface_hub >=0.28.1
    - platformdirs >=4.0.0
    - rasterio >=1.3
    - safetensors >=0.3.0
    - segmentation-models-pytorch >=0.5.0
    - timm >=0.9
    - pytorch >=2.3.0
    - tqdm >=4.0

test:
  imports:
    - omnicloudmask
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/DPIRD-DMA/OmniCloudMask
  summary: Python library for cloud and cloud shadow segmentation in high to moderate resolution satellite imagery
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - wrignj08
    - giswqs
